### ISSUE TITLE
The sidebar and the input area are widely spaced

### ISSUE THREAD

**Issue by VKWF** [gilbertohasnofb/typora-gothic-dark-theme#1]
![image](https://user-images.githubusercontent.com/38653497/113344029-27942e00-9363-11eb-9c73-67a08f8e0943.png)

**Comment by gilbertohasnofb** [comment]
Hi there. Although this theme is based on the default Gothic theme, I did make some alterations to the margins. I simply like it better with wider margins (I also altered my default `gothic.css` file). If you want the margins to behave exactly as in the default Gothic theme, there's a simple edit you can make in the file  `gothic-dark.css` (which should be located in your themes folder). Look for lines 454--469 (shown below)...:

```
#typora-source .CodeMirror-lines {
  max-width: 800px;
  padding-left: 70px;
  padding-right: 70px;
}

#write {
  display: block;
  visibility: visible;
  opacity: 1;
  transition: 0.3s;
  max-width: 800px;
  padding-left: 70px;
  padding-right: 70px;
  text-align: justify;
}
```

... and replace them with the following code:

```
#write {
	max-width: 914px;
	text-align: justify;
}
```

Hope this helps!

**Comment by VKWF** [comment]
You have succeeded in solving my problem，Thanks a lot!（My English is very poor, fortunately you understand my English  of Google translation...）

**Comment by gilbertohasnofb** [comment]
I'm happy to hear that solved your issue! Best wishes
